### ISSUE TITLE
modify activiti-app defaults in activiti-app.war

### ISSUE THREAD

**Issue by MevlutOzdemir** [OpenPj/alfresco-process-services-project-sdk#10]
How can we modify and overwrite values in the war that's build via `mvn clean install`?

For example, we want to modify the _beans-whitelist.conf_ that's part of the activiti-app.war.
`/activiti-app-overlay-war/overlays/com.activiti.activiti-app-1.11.0/WEB-INF/classes/activiti/beans-whitelist.conf`

**Comment by OpenPj** [comment]
Have you tried to put the new files under the following path?
/alfresco-process-services-project-sdk-master/activiti-app-overlay-war/src/main/webapp/WEB-INF/classes/activiti?
