### ISSUE TITLE
Run mvn docker:start as non-root?

### ISSUE THREAD

**Issue by mtwallach** [OpenPj/alfresco-process-services-project-sdk#31]
I have license at ./activiti-app-overlay-docker/src/main/docker/license/activiti.lic but it does not appear to be getting copied into the Docker container. Where does activiti.lic need to be? i don't see what is copying it to:  /root/.activiti/enterprise-license/activiti.lic 
(below error message)
Trying to load license from user home /root/.activiti/enterprise-license/activiti.lic

**Comment by OpenPj** [comment]
License files (activiti and Aspose) are copied in tomcat/lib that is the secondary classpath where APS is looking at for license.

Unfortunately this secondary classpath is hardcoded in the platform and it can't be configured. Anyway if you put licenses in tomcat/lib, APS starts correctly even if you see an error message in the log.
