### ISSUE TITLE
Debug mode with JPDA

### ISSUE THREAD

**Issue by flashboss** [OpenPj/alfresco-process-services-project-sdk#36]
Need to open a JPDA port to let the debug through JPDA starting by the customization of the Dockerfile from tomcat:9.0.56-jdk11-openjdk in the activiti-app-overlay-docker project customizing the CMD ["catalina.sh" "run"] line

**Comment by OpenPj** [comment]
Included in APS SDK 2.2.0 and APS SDK 1.8.0
