### ISSUE TITLE
pb with activiti license on nunit test of the 2.x branch

### ISSUE THREAD

**Issue by rbaudu** [OpenPj/alfresco-process-services-project-sdk#39]
Hi,
I have tested the new branch 2.x of the SDK on 2.1 and 2.2 and I always got a license error for the unit test.
The same license works with the docker container and with the master branch.

this is the trace of the error : 
09:38:05 [main] INFO  org.activiti.engine.impl.cfg.ProcessEngineConfigurationImpl  - Executing configure() of class com.alfresco.process.engine.cfg.AlfrescoProcessEngineConfigurator (priority:0)
09:38:05 [main] INFO  com.alfresco.license.LicenseHolder  - Using custom license loader to load license
09:38:06 [main] INFO  com.alfresco.license.LicenseHolder  - Trying to load license from user home C:\Users\Bluexml\.activiti\enterprise-license\activiti.lic
09:38:06 [main] ERROR com.alfresco.license.LicenseHolder  - License file could not be validated:
com.alfresco.license.LicenseException: Expected holder info is not present
        at com.alfresco.license.LicenseHolder.validateLicense(LicenseHolder.java:100)
        at com.alfresco.license.LicenseHolder.isLicenseValid(LicenseHolder.java:72)
        at com.alfresco.license.LicenseHolder.verifyLicense(LicenseHolder.java:85)
        at com.alfresco.process.engine.cfg.AlfrescoProcessEngineConfigurator.configure(AlfrescoProcessEngineConfigurator.java:32)

Any idea ?
thanks for your help
Regis

**Comment by OpenPj** [comment]
Currently for running unit test you have to put APS license file in this folder `<USER_HOME>/.activiti/enterprise-license`
Unfortunately this is a constraint of APS because this part related to the LicenseService is hardcoded.
I have to figure out how to load the license file in the classpath in the right way, then I have just created an issue for working on this #40

**Comment by rbaudu** [comment]
Thanks for the reply.
The problem is that my license is this folder <USER_HOME>/.activiti/enterprise-license as you see in the error message :  

`09:38:06 [main] INFO com.alfresco.license.LicenseHolder - Trying to load license from user home C:\Users\Bluexml\.activiti\enterprise-license\activiti.lic
`
USER_HOME=C:\Users\Bluexml

This same license file is used for the deployment under docker and it works.

thanks for your help
Regis

**Comment by OpenPj** [comment]
Resolved with the release [APS SDK 2.0.9 ](https://github.com/OpenPj/alfresco-process-services-project-sdk/releases/tag/v2.0.9)and [APS SDK 1.7.4](https://github.com/OpenPj/alfresco-process-services-project-sdk/releases/tag/v.1.7.4)
