### ISSUE TITLE
Add support for all the APS 2.x intermediate versions

### ISSUE THREAD

**Issue by OpenPj** [OpenPj/alfresco-process-services-project-sdk#53]
We have to add support for the following APS 2.x versions:

- 2.0.0
- 2.2.0.1
- 2.3.1

**Comment by OpenPj** [comment]
Hi,

that link is needed only for people that are currently using APS SDK earlier than 2.0.9 (for APS SDK 2.x) and earlier than 1.7.4 (for APS SDK 1.x). 

If you are using APS SDK 2.3.0 you don't need to follow that article because the license management is included.

**Comment by OpenPj** [comment]
Which version of the APS SDK are you using?

**Comment by OpenPj** [comment]
Anyway you probably need to download an updated license file for using APS 2.x

**Comment by nxmatar** [comment]
When I execute the command :
`mvn clean package`

![image](https://user-images.githubusercontent.com/13578159/166696965-a1e9eedc-b27b-4b17-8e70-5a641df37c98.png)

I installed this license on an APS 2.3.0 instance and it works.

**Comment by OpenPj** [comment]
Ok it seems that your license is invalid for APS 2.x, you have to update the license file downloading it from the Hyland portal.

**Comment by OpenPj** [comment]
Be sure to have just one license (activiti.lic and transform.lic) in the following paths:

- aps-extensions-jar/src/test/resources
- activiti-app-overlay-docker/src/main/docker/license

**Comment by nxmatar** [comment]
My license works well on an APS 2.3 standalone instance. I downloaded it from Hyland

![image](https://user-images.githubusercontent.com/13578159/166701679-f7da86d6-cccd-4768-9d1f-1d3ae7b2c196.png)

**Comment by OpenPj** [comment]
Ok but probably you could have something wrong in the APS SDK project, try to download from scratch APS SDK 2.1.2.
The license check is something included in the APS platform, the SDK is only using that component provided by Alfresco.
I'm also testing it today because I'm working on the next version for supporting the new version 2.3.1 and it works correctly.

**Comment by OpenPj** [comment]
Do you have a unique license bundle (activiti.lic and transform.lic) inside these folders?
- /license
- /aps-extensions-jar/src/test/resources
- /activiti-app-overlay-docker/src/main/docker/license

**Comment by nxmatar** [comment]
yes see screenshot 

![image](https://user-images.githubusercontent.com/13578159/166704512-778ceae5-cc34-4f21-ae2b-c738c14789f8.png)

**Comment by OpenPj** [comment]
Anyway it seems that the APS SDK is trying to use another license in your host machine at the following address:
C:\Users\mnian\.activiti\enterprise-license\activiti.lic

Please remove or rename that license from that path because otherwise the license checker is considering that one instead of the new one in the APS SDK project.

**Comment by OpenPj** [comment]
New versions of APS added in the latest release 2.1.3:
https://github.com/OpenPj/alfresco-process-services-project-sdk/releases/tag/v2.1.3
