### ISSUE TITLE
Add support for overriding logback.xml 

### ISSUE THREAD

**Issue by OpenPj** [OpenPj/alfresco-process-services-project-sdk#6]
It's needed a way to override with a unique configuration all the logging settings for different Extensions JAR Modules. 

For example with a logback.xml file in the Docker Module that will override any other specific configuration bundled with JARs.

**Comment by OpenPj** [comment]
Resolved in [v1.3.2](https://github.com/OpenPj/alfresco-process-services-project-sdk/releases/tag/v1.3.2)

**Comment by Marcuccio** [comment]
Questa issue è stata chiusa per errore oppure non è più necessario svilupparla?

**Comment by OpenPj** [comment]
Chiusa perché risolta e documentata nel readme, trovi il tutto sul master.
