### ISSUE TITLE
Rest controllers do not work if added  as part of aps-extension-jar 

### ISSUE THREAD

**Issue by dilip-chenani** [OpenPj/alfresco-process-services-project-sdk#65]
Rest controllers do not work if added  as part of aps-extension-jar. 
We created the custom rest endpoint following this document : https://docs.alfresco.com/process-services/latest/develop/dev-ext/#custom-rest-endpoints.  There is also a "note" mentioned in documentation about same : 
_**Note: Due to classloading, it is currently not possible to put jars with these custom rest endpoints in the global or common classpath (for example tomcat/lib for Tomcat). They should be put in the web application classpath (for example WEB-INF/lib).**_

**Comment by OpenPj** [comment]
Hi Dilip,
the `aps-extensions-jar` module is included in the WAR overlayed used by the container, so inside the `activiti-app.war` built by the APS SDK you will find the extensions JAR as expected, below the war overlay configuration included in the SDK:
https://github.com/OpenPj/alfresco-process-services-project-sdk/blob/master/activiti-app-overlay-war/pom.xml

APS SDK creates the `activiti-app.war` for you with the aps-extensions-jar inside the WAR. Then the custom WAR is included in the aps-current-project container. So if you follow the examples included in the APS SDK there is no problem at all.

If you are deploying your extensions without using the `activiti-app-overlay-war` and `activiti-app-overlay-docker` module included in the SDK, you have to build by yourself your own Maven project for your specific purpose.

Please let me know if you need more informations.

**Comment by dilip-chenani** [comment]
Thanks @OpenPj for quick response and details. 
I was creating a Dockerfile and was referring to this file from SDK : https://github.com/OpenPj/alfresco-process-services-project-sdk/blob/master/activiti-app-overlay-docker/src/main/docker/Dockerfile .
On line 20, it is moving the extensions jar to tomcat/lib. I was also trying the same thing. I used maven to build my extensions jar and then tried to move that jar Dockerfile to /tomcat/lib , and it was not working. Surprisingly, activiti-app.properties and license file do work if thrown at same location tomcat/lib. 

Do you know what could be the reason for it?

**Comment by OpenPj** [comment]
I added something in the latest commit 1.8.0-SNAPSHOT (main trunk) we don't have an official release yet, @dilip-chenani  feel free to clone the main trunk and test everything. Hopefully tomorrow we will have two new releases for both the SDKs 😄

**Comment by OpenPj** [comment]
If you are using APS SDK 1, I have just released APS SDK 1.8.0:
https://github.com/OpenPj/alfresco-process-services-project-sdk/releases/tag/v.1.8.0

APS SDK 2.2.0 is coming soon... 😄

**Comment by OpenPj** [comment]
Released with APS SDK 2.2.0 and APS SDK 1.8.0
